<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SarthakDELL" failures="1" tests="4" name="com.TestNG.Sep_24_2023_Day9_TestNG.AssertionFailures" time="15.740" errors="0" timestamp="30 Sep 2023 17:41:53 GMT" skipped="2">
  <testcase classname="com.TestNG.Sep_24_2023_Day9_TestNG.AssertionFailures" name="login" time="5.633"/>
  <testcase classname="com.TestNG.Sep_24_2023_Day9_TestNG.AssertionFailures" name="logout" time="10.107">
    <failure message="I just want to fail - my wish" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: I just want to fail - my wish
	at org.testng.Assert.fail(Assert.java:93)
	at com.TestNG.Sep_24_2023_Day9_TestNG.AssertionFailures.logout(AssertionFailures.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- logout -->
  <testcase classname="com.TestNG.Sep_24_2023_Day9_TestNG.AssertionFailures" name="continueButtonOnLogoutPage" time="0.000">
    <skipped/>
  </testcase> <!-- continueButtonOnLogoutPage -->
  <testcase classname="com.TestNG.Sep_24_2023_Day9_TestNG.AssertionFailures" name="logic1">
    <skipped/>
  </testcase> <!-- logic1 -->
</testsuite> <!-- com.TestNG.Sep_24_2023_Day9_TestNG.AssertionFailures -->
